### PR TITLE
prep release 2.0.0

### PR DESCRIPTION
**Pull request by mcrauwel**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@mcrauwel can you please regenerate the changelog with the github-changelog-generator? https://voxpupuli.org/blog/2017/01/13/github_changelog_generator-usage/

**Comment by mcrauwel** [comment]
Ok @bastelfreak, any other changes required to get this merged?

**Comment by bastelfreak** [comment]
Should be fine if we include https://github.com/voxpupuli/puppet-proxysql/pull/46 and rebase.

**Comment by mcrauwel** [comment]
@bastelfreak rebase done, changelog generator done...

**Comment by ekohl** [comment]
Looks like this needs a new rebase.

**Pull request merged**
