### PR TITLE
Add pattern normalization test

### PR DESCRIPTION
**Pull request by mat1010**
#### Pull Request (PR) description
To test the pattern normalization of #160 this PR extends the tests with a query rule that would fail the idempotence test without the fix of #160. Additionally the correct format of the query rule in the ProxySQL database will be tested as well.

#### This Pull Request (PR) fixes the following issues

Adds tests for #160

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I started the tests. If I forget to check back and merge then please ping me.

**Comment by mat1010** [comment]
Thank you @ekohl. There were some style issues with the original implementation of #160 - I updated it according to the ruby style guidelines, not sure why this wasn't failing in the initial test within #160

**Comment by ekohl** [comment]
We may have missed some style validation in our CI at some point or we've updated it since.

**Comment by ekohl** [comment]
Thanks for completing this!

**Comment by mat1010** [comment]
Great - thanks a lot for the rapid response and merge.

**Pull request merged**
