### PR TITLE
Release/1.1.1

### PR DESCRIPTION
**Pull request by mcrauwel**

### CODE REVIEW

**Comment by mcrauwel** [comment]
What did I do wrong? The pr is here still but the tag already exists.... I must have done something in the wrong order...

**Comment by bastelfreak** [comment]
Did you run "bundle exec rake travis_release" on the release/1.1.1 branch? It has do be done on master.

**Comment by mcrauwel** [comment]
Ah crap. Yeah I think that's what I dis wrong...

**Comment by bastelfreak** [comment]
don't worry. "Versionnumbers are cheap - use them" - @igalic. You can just create a new PR which updates the metadata.json and CHANGELOG.md

**Pull request closed without merging**
