### PR TITLE
Newer proxysql support

### PR DESCRIPTION
**Pull request by jadestorm**
#### Pull Request (PR) description
This PR adds very simple support for newer ProxySQL versions.  In my case I'm using 2.3 but I added the ones in between.  One big caveat is that I removed the cleanup of old versions in the process.  Frankly.. because it was going to be incredibly ugly code to clean up.  That said if you feel strongly about that, I can add it back.

It also adjusts the accepted regex patterns because stuff like: ^.*$ was not working because it had no word characters.

### CODE REVIEW

**Comment by jadestorm** [comment]
mmm ...  looks like I broke the testing that was expecting to see the purging of the old versions.  So -- please let me know which path you would like me to take: A. remove the cleanup of old versions like I've done (but I'll go back and fix the tests) or B. add back the cleanup of other versions and also adjust the tests accordingly.  I'm fine with either but wanted to ask first.

**Comment by jadestorm** [comment]
You know what -- after sleeping on it, it would be easy to put back that old version purge.  I'll do that -- please don't accept this as is.  =)

**Comment by jadestorm** [comment]
There we go.  If you're cool with it, ready for merging from my end.

**Review by ekohl — APPROVED** [review]
I'd be good if there was some acceptance test for this so we actually know it works, but this looks reasonable to me.

**Pull request merged**
