### PR TITLE
add support for 2.4.x

### LINKED ISSUE #190: ProxySQL 2.4.x not supported
## How to reproduce (e.g Puppet code you use)

```puppet
  $override_settings = {

  }

  $admin_password = Sensitive('something_secret')
  $monitor_password = Sensitive('not_quite_as_secret')

  class { '::proxysql':
    listen_port              => 3306,
    admin_password           => $admin_password,
    monitor_password         => $monitor_password,
    override_config_settings => $override_settings,
    version                  => "2.4.5"
  }
```

## What are you seeing
No repository available

## What behaviour did you expect instead
Ability to install > 2.3.x versions of ProxySQL

## Output log
```
Evaluation Error: Error while evaluating a Function Call, Unsupported `proxysql::version` 2.4.5 
```

### PR DESCRIPTION
**Pull request by jackdpeterson**
Closes #190

### CODE REVIEW

**Comment by jackdpeterson** [comment]
I don't see any acceptance tests for 2.3.x that explicitly ensure that say 2.3.2 is installed; I'd like to add one that tests that 2.4.5 is installed when specified. Got a good example I can use to enrich this PR @oranenj or @dalen (not sure who to @ here :-))?

**Comment by nicolas-morel-claranet** [comment]
Hello,

Do you have any news about this PR ? I need it to install Proxysql on jammy

Thanks

**Comment by alnet** [comment]
This seems like a small fix to a problem several folks are running into that has been sitting for 8 months now. Is there a reason it can't be merged and published on puppet forge?

**Comment by mwinkens** [comment]
This is also an issue for version 2.5.x now, there is currently no jammy version we are able to install.
[v2.3.x does not exist for jammy](https://repo.proxysql.com/ProxySQL/proxysql-2.3.x/jammy/)
[v2.4.x](https://repo.proxysql.com/ProxySQL/proxysql-2.4.x/jammy/)
[v2.5.x](https://repo.proxysql.com/ProxySQL/proxysql-2.5.x/jammy/)

**Comment by jackdpeterson** [comment]
This seems like an easy one to merge in IMO. I don't normally do much puppet development in general; just scratching my own itch when I want to update my ProxySQL instances. Probably going to move ProxySQL fully to docker anyways though since this is a much slower build process these days.

**Review by mcrauwel — APPROVED** [review]

**Pull request merged**
