### PR TITLE
fix bug in types that int[0,1] were boolean

### PR DESCRIPTION
**Pull request by MaxFedotov**
Hello,

there is some discrepancy between values in types\resource and proxysql. By default some of them are boolean in types, had [0,1] regexp checks in resouce and are defined as INT CHECK (negate_match_pattern IN (0,1)) in proxysql. 
Because of it is impossible to set them in manifest

For example, setting `"transaction_persistent": 0` for user will lead to:
`Evaluation Error: Error while evaluating a Method call, Class[Db::Proxysql]: parameter 'mysql_users' index 0 entry 'app' entry 'transaction_persistent' expects a Boolean value, got Integer`

and setting  `"transaction_persistent": false` for user will lead to:
`Failed to apply catalog: Parameter transaction_persistent failed on Proxy_mysql_user[app]: Invalid value false. Valid values match /[01]/.`

### CODE REVIEW

**Comment by alexjfisher** [comment]
@MaxFedotov Sorry, I merged https://github.com/voxpupuli/puppet-proxysql/pull/88 before seeing this PR also existed!  Yours actually looks more complete.  If you can rebase it, I'll look at getting it merged soon after.

**Comment by alexjfisher** [comment]
And thanks for all your other PRs.  I'll try to get them reviewed and progressed.  If things are stalling, stop by the puppet community slack `#voxpupuli` channel or IRC Freenode `#voxpupuli`.

**Comment by dhoppe** [comment]
@alexjfisher This pull request is more strict than #88, because it expects a very specific value. In my opinion this pull request can be merged. Any objections?

**Comment by alexjfisher** [comment]
@dhoppe Agreed.  I've rebased again and will now merge.

@MaxFedotov Thanks!

**Pull request merged**
