### PR TITLE
modulesync 5.3.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 5.1.0

### CODE REVIEW

**Comment by ekohl** [comment]
Updated to 5.2.0.

**Review by ekohl — APPROVED** [review]
I updated it to modulesync 5.3.0, which is quite trivial. Let's get this merged once CI is green.

**Comment by saz** [comment]
Looks like as if a fact is missing:

```

Error: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /etc/puppetlabs/code/modules/proxysql/manifests/params.pp, line: 21, column: 73) on node ubuntu1804-64.example.com

```

**Comment by ekohl** [comment]
That's because it needs lsb-release installed on Ubuntu with Facter 3 (to provide the codename distro codename fact). I'll push an update.

**Comment by saz** [comment]
> That's because it needs lsb-release installed on Ubuntu with Facter 3 (to provide the codename distro codename fact). I'll push an update.

Ah, wasn't aware of that. Thanks for the explanation!

**Comment by ekohl** [comment]
Technically until Facter 4 lsb-release was always needed for various OS facts, but the container image used to come preinstalled with it. Now it no longer is on Ubuntu. Facter 4 learned to parse `/etc/os-release` for the same information.

**Pull request merged**
